# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db26c2761f3b03fab99f99541aa689c4309a28208a27f2e6b22e1e9733ba0c30ced09d10db9b8d38c3e7049aab0903ea67e7f959cd18537f5acd3257c2ab1774

test:
  secret_key_base: 317d4e5c61f57f9ac044dba35613c852a0a47c493a99b747a2dd37000e4d3516c16e2b8706b4afa76a62c6216e146386716e0c6653723187b9061143f0764dc7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
